In [1]:
import numpy as np

In [2]:
l = ["mohit",1,2,3,4]

In [3]:
np.array(l)

array(['mohit', '1', '2', '3', '4'], dtype='<U11')

In [4]:
l1 = [[1,2,3],[2,3,4]]

In [5]:
a = np.array(l1)

In [6]:
a

array([[1, 2, 3],
       [2, 3, 4]])

In [7]:
a[0][2]

3

In [8]:
l = [1,2,3,4]

In [9]:
l

[1, 2, 3, 4]

In [10]:
a = np.array(l,ndmin = 2)

In [11]:
a[0]

array([1, 2, 3, 4])

In [12]:
a = np.fromfunction(lambda x,y,z,a : a*x*y*z,(3,3,3,3))

In [13]:
a

array([[[[ 0.,  0.,  0.],
         [ 0.,  0.,  0.],
         [ 0.,  0.,  0.]],

        [[ 0.,  0.,  0.],
         [ 0.,  0.,  0.],
         [ 0.,  0.,  0.]],

        [[ 0.,  0.,  0.],
         [ 0.,  0.,  0.],
         [ 0.,  0.,  0.]]],


       [[[ 0.,  0.,  0.],
         [ 0.,  0.,  0.],
         [ 0.,  0.,  0.]],

        [[ 0.,  0.,  0.],
         [ 0.,  1.,  2.],
         [ 0.,  2.,  4.]],

        [[ 0.,  0.,  0.],
         [ 0.,  2.,  4.],
         [ 0.,  4.,  8.]]],


       [[[ 0.,  0.,  0.],
         [ 0.,  0.,  0.],
         [ 0.,  0.,  0.]],

        [[ 0.,  0.,  0.],
         [ 0.,  2.,  4.],
         [ 0.,  4.,  8.]],

        [[ 0.,  0.,  0.],
         [ 0.,  4.,  8.],
         [ 0.,  8., 16.]]]])

In [14]:
a.ndim

4

In [15]:
a.size

81

In [16]:
a.shape

(3, 3, 3, 3)

In [17]:
a.dtype

dtype('float64')

In [18]:
np.random.rand(4,5)

array([[0.83235745, 0.70447081, 0.3937946 , 0.62252916, 0.59162294],
       [0.258983  , 0.00143406, 0.6090631 , 0.31225497, 0.36293847],
       [0.48813233, 0.21612466, 0.54138721, 0.8963198 , 0.60611392],
       [0.81834816, 0.65884662, 0.07221264, 0.51771581, 0.98878066]])

In [19]:
np.random.randint(45,89)

67

In [20]:
np.random.randn(5,5) #create normal distribution data


array([[ 0.6775449 ,  0.76490743,  0.70870846, -1.39106044,  0.75196162],
       [-1.28463293,  1.39782633, -0.43420261, -0.83281785,  0.7847356 ],
       [ 1.09871884, -0.16803845,  1.90673601,  1.53737434,  0.23225157],
       [-0.35653642,  0.87530286, -1.51534816, -0.84406297,  0.3676801 ],
       [ 0.02498328, -0.38604084,  1.09439105,  1.40222976, -1.24973671]])

In [21]:
a

array([[[[ 0.,  0.,  0.],
         [ 0.,  0.,  0.],
         [ 0.,  0.,  0.]],

        [[ 0.,  0.,  0.],
         [ 0.,  0.,  0.],
         [ 0.,  0.,  0.]],

        [[ 0.,  0.,  0.],
         [ 0.,  0.,  0.],
         [ 0.,  0.,  0.]]],


       [[[ 0.,  0.,  0.],
         [ 0.,  0.,  0.],
         [ 0.,  0.,  0.]],

        [[ 0.,  0.,  0.],
         [ 0.,  1.,  2.],
         [ 0.,  2.,  4.]],

        [[ 0.,  0.,  0.],
         [ 0.,  2.,  4.],
         [ 0.,  4.,  8.]]],


       [[[ 0.,  0.,  0.],
         [ 0.,  0.,  0.],
         [ 0.,  0.,  0.]],

        [[ 0.,  0.,  0.],
         [ 0.,  2.,  4.],
         [ 0.,  4.,  8.]],

        [[ 0.,  0.,  0.],
         [ 0.,  4.,  8.],
         [ 0.,  8., 16.]]]])

In [22]:
a.size

81

In [23]:
a.reshape(9,9)

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  2.,  0.,  2.,  4.],
       [ 0.,  0.,  0.,  0.,  2.,  4.,  0.,  4.,  8.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  2.,  4.,  0.,  4.,  8.],
       [ 0.,  0.,  0.,  0.,  4.,  8.,  0.,  8., 16.]])

In [24]:
list(range(2,10))

[2, 3, 4, 5, 6, 7, 8, 9]

In [25]:
a = np.arange(2,10,.2)

In [26]:
a

array([2. , 2.2, 2.4, 2.6, 2.8, 3. , 3.2, 3.4, 3.6, 3.8, 4. , 4.2, 4.4,
       4.6, 4.8, 5. , 5.2, 5.4, 5.6, 5.8, 6. , 6.2, 6.4, 6.6, 6.8, 7. ,
       7.2, 7.4, 7.6, 7.8, 8. , 8.2, 8.4, 8.6, 8.8, 9. , 9.2, 9.4, 9.6,
       9.8])

In [27]:
a[5]

3.000000000000001

In [28]:
a[a>5]

array([5. , 5.2, 5.4, 5.6, 5.8, 6. , 6.2, 6.4, 6.6, 6.8, 7. , 7.2, 7.4,
       7.6, 7.8, 8. , 8.2, 8.4, 8.6, 8.8, 9. , 9.2, 9.4, 9.6, 9.8])

In [29]:
v = np.random.rand(8,5)

In [30]:
v

array([[0.20803369, 0.31418176, 0.93157269, 0.88069857, 0.43995012],
       [0.85583469, 0.73532466, 0.31274438, 0.40363012, 0.63640668],
       [0.4473323 , 0.04132776, 0.88905546, 0.63190213, 0.71176179],
       [0.8081671 , 0.65096986, 0.70973586, 0.54105103, 0.27270171],
       [0.06819845, 0.46071246, 0.84976567, 0.36918179, 0.35191527],
       [0.95545911, 0.96631624, 0.57780022, 0.11429035, 0.12306424],
       [0.49618244, 0.33969835, 0.98368645, 0.1575954 , 0.0147296 ],
       [0.23845776, 0.69996772, 0.12052527, 0.82777299, 0.74740053]])

In [31]:
v[[1,2],2]

array([0.31274438, 0.88905546])

In [32]:
a = np.array([[2,3],[8,9]])
b = np.array([[7,8],[6,5]])

In [33]:
a

array([[2, 3],
       [8, 9]])

In [34]:
b

array([[7, 8],
       [6, 5]])

In [35]:
a*b

array([[14, 24],
       [48, 45]])

In [36]:
m = a@b

In [37]:
m

array([[ 32,  31],
       [110, 109]])

In [38]:
m/0

C:\Users\mohit\AppData\Local\Temp/ipykernel_26240/3791875896.py:1: RuntimeWarning: divide by zero encountered in true_divide
  m/0


array([[inf, inf],
       [inf, inf]])

In [39]:
np.zeros((6,8))

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [40]:
np.zeros(9)

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [41]:
np.ones((5,9))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [42]:
np.ones(8)

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [43]:
np.linspace(2,3)

array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
       2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
       2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
       2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
       2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
       2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
       2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
       2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
       2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
       2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ])

In [46]:
np.random.random()

0.6550420584252595

In [57]:
np.random.seed(2)
np.random.random()

0.43599490214200376

In [63]:
np.random.uniform(3,10)

8.042271454095108

In [65]:
np.random.uniform(3,10,8)

array([9.18314264, 7.36570545, 8.25659704, 5.44228839, 4.88949524,
       9.27120353, 5.99663833, 9.75388033])

In [68]:
np.random.uniform(2,10,10).reshape(2,5)

array([[2.02296262, 6.93715931, 4.61315921, 6.21646482, 9.08753679],
       [4.85815808, 9.26828121, 6.98688093, 2.12656994, 9.43549787]])

In [74]:
np.random.randint(3,10,20).reshape(2,5,2)

array([[[8, 4],
        [5, 7],
        [6, 3],
        [9, 3],
        [8, 7]],

       [[5, 7],
        [9, 5],
        [3, 8],
        [6, 3],
        [3, 7]]])

In [75]:
a = np.random.randint(2,30,15)

In [76]:
a

array([15, 20, 17, 11,  2, 14, 21, 26, 19, 12, 22, 14, 17, 29, 16])

In [78]:
a.max()

29

In [79]:
a.min()

2

In [81]:
np.argmax(a)

13

In [82]:
np.argmin(a)

4

In [83]:
np.random.randint(2,56,8)

array([53, 21, 28, 45, 24,  9, 37, 55])

In [84]:
np.where(a%2 == 1,-1,a)

array([-1, 20, -1, -1,  2, 14, -1, 26, -1, 12, 22, 14, -1, -1, 16])

In [87]:
a = np.random.randint(2,70,12)

In [90]:
a = np.sort(a)

In [91]:
a

array([19, 19, 24, 30, 32, 37, 40, 41, 44, 62, 66, 68])

In [92]:
np.percentile(a,50)

38.5

In [93]:
np.percentile(a,100)

68.0